# Generated by Django 4.2.4 on 2023-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150)),
                ('product_description', models.TextField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('LP', 'Laptop'), ('SM', 'Smartphone'), ('BK', 'Bike'), ('WH', 'Watch'), ('TM', 'Trimmer'), ('CH', 'Charger')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
