# Generated by Django 4.2.4 on 2023-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
